export { MarketingHeader } from "./Header";
export { Hero } from "./Hero";
export { PainPoints } from "./PainPoints";
export { Features } from "./Features";
export { Modules } from "./Modules";
export { CTA } from "./CTA";
export { Footer } from "./Footer";
export { Pricing } from "./Pricing";
export { ScrollReveal } from "./ScrollReveal";
